services:
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - algorank-network

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=algorank
      - DB_PASSWORD=algorank123
      - DB_NAME=algorank
    depends_on:
      - db
    networks:
      - algorank-network

  executor:
    build:
      context: ./Executor
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Problem:/app/Problem:ro
      - ./Solutions:/app/Solutions
    networks:
      - algorank-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=algorank
      - POSTGRES_PASSWORD=algorank123
      - POSTGRES_DB=algorank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - algorank-network

volumes:
  postgres_data:

networks:
  algorank-network:
    driver: bridge